#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_SK_Skull

#include "Basic.hpp"

#include "AnimBP_SK_Skull_classes.hpp"
#include "AnimBP_SK_Skull_parameters.hpp"


namespace SDK
{

// Function AnimBP_SK_Skull.AnimBP_SK_Skull_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAnimBP_SK_Skull_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_SK_Skull_C", "AnimGraph");

	Params::AnimBP_SK_Skull_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AnimBP_SK_Skull.AnimBP_SK_Skull_C.ExecuteUbergraph_AnimBP_SK_Skull
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_SK_Skull_C::ExecuteUbergraph_AnimBP_SK_Skull(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_SK_Skull_C", "ExecuteUbergraph_AnimBP_SK_Skull");

	Params::AnimBP_SK_Skull_C_ExecuteUbergraph_AnimBP_SK_Skull Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

