#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Anvil

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Anvil.BP_Anvil_C
// 0x0000 (0x02E8 - 0x02E8)
class ABP_Anvil_C final : public ACrabAnvil
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Anvil_C">();
	}
	static class ABP_Anvil_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Anvil_C>();
	}
};
static_assert(alignof(ABP_Anvil_C) == 0x000008, "Wrong alignment on ABP_Anvil_C");
static_assert(sizeof(ABP_Anvil_C) == 0x0002E8, "Wrong size on ABP_Anvil_C");

}

