#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Beam_BeamShot

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Beam_BeamShot.BP_Beam_BeamShot_C
// 0x0000 (0x0308 - 0x0308)
class ABP_Beam_BeamShot_C final : public ACrabBeam
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Beam_BeamShot_C">();
	}
	static class ABP_Beam_BeamShot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Beam_BeamShot_C>();
	}
};
static_assert(alignof(ABP_Beam_BeamShot_C) == 0x000008, "Wrong alignment on ABP_Beam_BeamShot_C");
static_assert(sizeof(ABP_Beam_BeamShot_C) == 0x000308, "Wrong size on ABP_Beam_BeamShot_C");

}

