#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BeamTurret

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BeamTurret.BP_BeamTurret_C
// 0x0000 (0x0348 - 0x0348)
class ABP_BeamTurret_C final : public ACrabTurret
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BeamTurret_C">();
	}
	static class ABP_BeamTurret_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BeamTurret_C>();
	}
};
static_assert(alignof(ABP_BeamTurret_C) == 0x000008, "Wrong alignment on ABP_BeamTurret_C");
static_assert(sizeof(ABP_BeamTurret_C) == 0x000348, "Wrong size on ABP_BeamTurret_C");

}

