#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Enemy_Pumpkin

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Enemy_Pumpkin.BP_Enemy_Pumpkin_C
// 0x0000 (0x0990 - 0x0990)
class ABP_Enemy_Pumpkin_C : public ACrabEnemyC
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Enemy_Pumpkin_C">();
	}
	static class ABP_Enemy_Pumpkin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Enemy_Pumpkin_C>();
	}
};
static_assert(alignof(ABP_Enemy_Pumpkin_C) == 0x000010, "Wrong alignment on ABP_Enemy_Pumpkin_C");
static_assert(sizeof(ABP_Enemy_Pumpkin_C) == 0x000990, "Wrong size on ABP_Enemy_Pumpkin_C");

}

