#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EliteBeamSkull_VerticalBeam

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_EliteBeamSkull_VerticalBeam.BP_EliteBeamSkull_VerticalBeam_C
// 0x0000 (0x0308 - 0x0308)
class ABP_EliteBeamSkull_VerticalBeam_C final : public ACrabBeam
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_EliteBeamSkull_VerticalBeam_C">();
	}
	static class ABP_EliteBeamSkull_VerticalBeam_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EliteBeamSkull_VerticalBeam_C>();
	}
};
static_assert(alignof(ABP_EliteBeamSkull_VerticalBeam_C) == 0x000008, "Wrong alignment on ABP_EliteBeamSkull_VerticalBeam_C");
static_assert(sizeof(ABP_EliteBeamSkull_VerticalBeam_C) == 0x000308, "Wrong size on ABP_EliteBeamSkull_VerticalBeam_C");

}

