#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HarvestArea_TEST

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_HarvestArea_TEST.BP_HarvestArea_TEST_C
// 0x0000 (0x02B0 - 0x02B0)
class ABP_HarvestArea_TEST_C final : public ACrabHarvestArea
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_HarvestArea_TEST_C">();
	}
	static class ABP_HarvestArea_TEST_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_HarvestArea_TEST_C>();
	}
};
static_assert(alignof(ABP_HarvestArea_TEST_C) == 0x000008, "Wrong alignment on ABP_HarvestArea_TEST_C");
static_assert(sizeof(ABP_HarvestArea_TEST_C) == 0x0002B0, "Wrong size on ABP_HarvestArea_TEST_C");

}

