#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhysicsActor_Coconut

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PhysicsActor_Coconut.BP_PhysicsActor_Coconut_C
// 0x0000 (0x0278 - 0x0278)
class ABP_PhysicsActor_Coconut_C final : public ACrabPhysicsActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PhysicsActor_Coconut_C">();
	}
	static class ABP_PhysicsActor_Coconut_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PhysicsActor_Coconut_C>();
	}
};
static_assert(alignof(ABP_PhysicsActor_Coconut_C) == 0x000008, "Wrong alignment on ABP_PhysicsActor_Coconut_C");
static_assert(sizeof(ABP_PhysicsActor_Coconut_C) == 0x000278, "Wrong size on ABP_PhysicsActor_Coconut_C");

}

