#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SpawnPoint_Enemy

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SpawnPoint_Enemy.BP_SpawnPoint_Enemy_C
// 0x0000 (0x0238 - 0x0238)
class ABP_SpawnPoint_Enemy_C final : public ACrabSpawnPoint
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SpawnPoint_Enemy_C">();
	}
	static class ABP_SpawnPoint_Enemy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SpawnPoint_Enemy_C>();
	}
};
static_assert(alignof(ABP_SpawnPoint_Enemy_C) == 0x000008, "Wrong alignment on ABP_SpawnPoint_Enemy_C");
static_assert(sizeof(ABP_SpawnPoint_Enemy_C) == 0x000238, "Wrong size on ABP_SpawnPoint_Enemy_C");

}

