#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SK_Crab_AnimBP_Enemy

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function SK_Crab_AnimBP_Enemy.SK_Crab_AnimBP_Enemy_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct SK_Crab_AnimBP_Enemy_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(SK_Crab_AnimBP_Enemy_C_AnimGraph) == 0x000008, "Wrong alignment on SK_Crab_AnimBP_Enemy_C_AnimGraph");
static_assert(sizeof(SK_Crab_AnimBP_Enemy_C_AnimGraph) == 0x000010, "Wrong size on SK_Crab_AnimBP_Enemy_C_AnimGraph");
static_assert(offsetof(SK_Crab_AnimBP_Enemy_C_AnimGraph, AnimGraph_0) == 0x000000, "Member 'SK_Crab_AnimBP_Enemy_C_AnimGraph::AnimGraph_0' has a wrong offset!");

// Function SK_Crab_AnimBP_Enemy.SK_Crab_AnimBP_Enemy_C.ExecuteUbergraph_SK_Crab_AnimBP_Enemy
// 0x0014 (0x0014 - 0x0000)
struct SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetRelevantAnimTime_ReturnValue;          // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_1;         // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_2;         // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_MapRangeClamped_ReturnValue;              // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue_1;            // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy) == 0x000004, "Wrong alignment on SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy");
static_assert(sizeof(SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy) == 0x000014, "Wrong size on SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy");
static_assert(offsetof(SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy, EntryPoint) == 0x000000, "Member 'SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy::EntryPoint' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy, CallFunc_GetRelevantAnimTime_ReturnValue) == 0x000004, "Member 'SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy::CallFunc_GetRelevantAnimTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000008, "Member 'SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy, CallFunc_Greater_FloatFloat_ReturnValue_1) == 0x000009, "Member 'SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy::CallFunc_Greater_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy, CallFunc_Greater_FloatFloat_ReturnValue_2) == 0x00000A, "Member 'SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy::CallFunc_Greater_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy, CallFunc_Less_FloatFloat_ReturnValue) == 0x00000B, "Member 'SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy::CallFunc_Less_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy, CallFunc_MapRangeClamped_ReturnValue) == 0x00000C, "Member 'SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy::CallFunc_MapRangeClamped_ReturnValue' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy, CallFunc_Less_FloatFloat_ReturnValue_1) == 0x000010, "Member 'SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy::CallFunc_Less_FloatFloat_ReturnValue_1' has a wrong offset!");

}

