#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Crosshair

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Crosshair.UI_Crosshair_C
// 0x0020 (0x0368 - 0x0348)
class UUI_Crosshair_C final : public UCrabCrosshairUI
{
public:
	class UImage*                                 EliminationHitmarkerImage;                         // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_1;                                           // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_63;                                          // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Crosshair_C">();
	}
	static class UUI_Crosshair_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Crosshair_C>();
	}
};
static_assert(alignof(UUI_Crosshair_C) == 0x000008, "Wrong alignment on UUI_Crosshair_C");
static_assert(sizeof(UUI_Crosshair_C) == 0x000368, "Wrong size on UUI_Crosshair_C");
static_assert(offsetof(UUI_Crosshair_C, EliminationHitmarkerImage) == 0x000348, "Member 'UUI_Crosshair_C::EliminationHitmarkerImage' has a wrong offset!");
static_assert(offsetof(UUI_Crosshair_C, Image) == 0x000350, "Member 'UUI_Crosshair_C::Image' has a wrong offset!");
static_assert(offsetof(UUI_Crosshair_C, Image_1) == 0x000358, "Member 'UUI_Crosshair_C::Image_1' has a wrong offset!");
static_assert(offsetof(UUI_Crosshair_C, Image_63) == 0x000360, "Member 'UUI_Crosshair_C::Image_63' has a wrong offset!");

}

