#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Enhancement_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Enhancement_OLD.UI_Enhancement_OLD_C
// 0x0000 (0x02D8 - 0x02D8)
class UUI_Enhancement_OLD_C final : public UCrabEnhancementUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Enhancement_OLD_C">();
	}
	static class UUI_Enhancement_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Enhancement_OLD_C>();
	}
};
static_assert(alignof(UUI_Enhancement_OLD_C) == 0x000008, "Wrong alignment on UUI_Enhancement_OLD_C");
static_assert(sizeof(UUI_Enhancement_OLD_C) == 0x0002D8, "Wrong size on UUI_Enhancement_OLD_C");

}

