#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Revival_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Revival_OLD.UI_Revival_OLD_C
// 0x0000 (0x02D0 - 0x02D0)
class UUI_Revival_OLD_C final : public UCrabRevivalUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Revival_OLD_C">();
	}
	static class UUI_Revival_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Revival_OLD_C>();
	}
};
static_assert(alignof(UUI_Revival_OLD_C) == 0x000008, "Wrong alignment on UUI_Revival_OLD_C");
static_assert(sizeof(UUI_Revival_OLD_C) == 0x0002D0, "Wrong size on UUI_Revival_OLD_C");

}

